# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/session_tests/05_tests_utils.ipynb.

# %% auto 0
__all__ = ['test_session']

# %% ../../nbs/session_tests/05_tests_utils.ipynb 3
#| output: false
import numpy as np
import tempfile
from pandas import DataFrame
from pathlib import Path
from typing import List, Optional, Iterable, Dict, no_type_check, Type
import pandas as pd

from graph_rewrite import draw
from ..utils import assert_df
from ..session import Session

# %% ../../nbs/session_tests/05_tests_utils.ipynb 4
def test_session(
    context,
    queries,
    expected_outputs,# either a set of tuples or (set of tuples,list of columns)
    ie_funcs=None,# List of [name,func,in_scheme,out_scheme]
    csvs=None,# List of [name,df]
    debug=False,
    ):
    sess=Session()
    # init session with context

    # add csvs

    # register functions

    for query,expected in zip(queries,expected_outputs):
        if debug:
            print(query)
            q,root = sess.plan_query(query)
            draw(q)
            res = sess.execute_plan(q)
        else:
            res = context.export(query)
        if isinstance(expected,tuple):
            values,columns = expected
            assert_df(res,values,columns)
        else:
            assert_df(res,expected)
