# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/tutorials/001_basic_tasks.ipynb.

# %% auto 0
__all__ = []

# %% ../../nbs/tutorials/001_basic_tasks.ipynb 4
# importing dependencies
import re
import pandas as pd
from pandas import DataFrame
from pathlib import Path
from .. import get_magic_session,Session,Span

