# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/040_magic_system.ipynb.

# %% auto 0
__all__ = ['spannerlogMagic']

# %% ../nbs/040_magic_system.ipynb 3
from typing import Optional

from IPython.core.magic import (Magics, magics_class, line_cell_magic)

# %% ../nbs/040_magic_system.ipynb 4
@magics_class
class spannerlogMagic(Magics):
    @line_cell_magic
    def spannerlog(self, line: str, cell: Optional[str] = None) -> None:
        # import locally to prevent circular import issues
        from spannerlib import magic_session

        if cell:
            magic_session.run_commands(cell, print_results=True)
        else:
            magic_session.run_commands(line, print_results=True)

