project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
  sidebar:
    search: true
    style: docked
    collapse-level: 1

metadata-files: [nbdev.yml, sidebar.yml]