name: CI
on: [workflow_dispatch, pull_request, push]

env:
  PYTHON_VERSION: 3.12

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install Protoc
        uses: arduino/setup-protoc@v3

      - name: Use nbdev CI Workflow
        uses: fastai/workflows/nbdev-ci@master
        with:
          # The python version that nbdev ci must run on must match the python version used 
          version: ${{ env.PYTHON_VERSION }}
          skip_test: true
          
      - name: Run Tests
        run: |
          find $(python3 -c 'import sysconfig; print(sysconfig.get_paths()["purelib"])') -name rust_grpc_server -exec sh -c 'current_rpath=$(patchelf --print-rpath "{}"); binary_dir=$(dirname "{}"); new_rpath="${current_rpath:+$current_rpath:}$binary_dir/target/release"; patchelf --set-rpath "$new_rpath" "{}"' \;
          # Capture both stdout and stderr to a temporary file
          python nbdev_test.py > /tmp/test_output.txt
          cat /tmp/test_output.txt  # Print the test output for debugging purposes

          if grep -q "nbdev Tests Failed On The Following Notebooks:" /tmp/test_output.txt; then
            echo "nbdev Tests Failed"
            exit 1
          fi
        shell: bash